#ifndef can_HEADER
#define can_HEADER

//
// can_ui.h - User interface object and function declarations.
// This file was generated by `gxv++' from `can.G'.
// DO NOT EDIT BY HAND.
//

extern Attr_attribute   INSTANCE;


class can_window1_objects {

public:
        Xv_opaque       window1;
        Xv_opaque       canvas1;
        Xv_opaque       controls1;
        Xv_opaque       button1;
        Xv_opaque       button2;
        Xv_opaque       button3;

        virtual void    objects_initialize(Xv_opaque);

        virtual Xv_opaque       window1_create(Xv_opaque);
        virtual Xv_opaque       canvas1_create(Xv_opaque);
        virtual Xv_opaque       controls1_create(Xv_opaque);
        virtual Xv_opaque       button1_create(Xv_opaque);
        virtual Xv_opaque       button2_create(Xv_opaque);
        virtual Xv_opaque       button3_create(Xv_opaque);
};
#endif

