set timeout 1
set compteur 1
set nom_process_courant ""

proc process_start {process} {
    global spawn_id
    global compteur
    global nom_process_courant

    set nom_process_courant $process
    set compteur 1
    spawn test$process
    send_log "Executing test$process \n"
    expect {
	 -re "Starting test$process" { }
	 timeout { perror "Failed to spawn test$process (timeout)"; exit 1 }
    }
}

proc process_exit {} {
    send "1\n1\n1\n"
}
proc process_version {} {
}

expect_after {
    timeout {fail "$test (timeout)"}
}



proc process_test {chaine} {
    global compteur
    global nom_process_courant

    set test "$compteur: $chaine"
    send "1\n"

    set testok [exec cat -v output.ok/$nom_process_courant-test-$compteur ]
    regsub -all "\n" $testok "\r\n" testok

    set compteur [expr $compteur + 1]
    
    send_log "\nla variable testok contient\n"
    send_log $testok
    send_log "\nc'est pour verifier\n"
    expect {
	    -ex "$testok" {pass "$test"} 
    }
}


