process_start Ponderation

process_test "constructeur par defaut"
process_test "constructeur à partir d'un tableau de probabilités"
process_test "operateur +="
process_test "operateur +"
process_test "methodes setPonderation"
process_test "test exception sur setPonderation(7,2)"
process_test "methodes getPonderation"
process_test "test exception sur getPonderation(7,2)"
process_test "methode getModule"


