process_start RegleExclusion

process_test "constructeur avec arguments"
process_test "methode setNom"
process_test "methode getNom"
process_test "methode setContrainte"
process_test "methode setDeplacement"
process_test "methode getDeplacement"
process_test "methode getContrainte"

match_max 200000

process_test "la rotation"
process_test "la rotation  setContrainte et setDeplacement"
process_test "methode ajoutPaire avec deux arguments"
process_test "constructeur sans arguments"
process_test "test d'acces interdit (vieux bug)"
process_test "methode ajoutPaire avec un arguments"


