.KEEP_STATE:

all: chargf chargmf joindre voirjoint voir

chargf: chargf.c
	gcc -g -Wall chargf.c -o chargf

chargmf: chargmf.c
	gcc -g -Wall chargmf.c -o chargmf

joindre: joindre.c
	gcc -g -Wall joindre.c -o joindre

voirjoint: voirjoint.c
	gcc -g -Wall voirjoint.c -o voirjoint

voir: voir.c
	gcc -g -Wall voir.c -o voir;

clean:
	\rm *~
	\rm chargmf chargf