/* Automatically generated by po2tbl.sed from grany.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Close", 2},
  {"version ", 3},
  {"is a simulator of cellular automata for the granular environments", 4},
  {"Authors", 5},
  {"This program is ", 6},
  {"For further information, consult", 7},
  {"About Grany-3...", 8},
  {"_Scene editor", 9},
  {"<alt>s", 10},
  {"_Borders editor", 11},
  {"<alt>b", 12},
  {"_Rules editor", 13},
  {"<alt>r", 14},
  {"_Updatable parameters", 15},
  {"<alt>u", 16},
  {"_Tools", 17},
  {"<alt>t", 18},
  {"St_op", 19},
  {"<alt>o", 20},
  {"_Play", 21},
  {"<alt>p", 22},
  {"P_ause", 23},
  {"<alt>a", 24},
  {"Recor_d", 25},
  {"<alt>d", 26},
  {"_Control", 27},
  {"<alt>c", 28},
  {"Stop", 29},
  {"Play", 30},
  {"Pause", 31},
  {"Record", 32},
  {"Ready.", 33},
  {"\
I detected you don't have `~/.grany' directory,\n\
but I can't find my installing script...\n\
I tried: ", 34},
  {"\
No `~/.grany' directory. Welcome to Grany, new user! Let's make your very \
own grany directory...", 35},
  {"Invoking my install script: ", 36},
  {"Installation successful. Enjoy!", 37},
  {"\
A directory `~/.grany' and some subdirs have been created.\n\
Please put your creations in its subdirectories.\n\
NB: through each window you can access Help / Newbie help which will help \
you begin with Grany.", 38},
  {"\
I detected you don't have `~/.grany' directory,\n\
but I failed while invoking my script...\n\
I tried: ", 39},
  {"\
This is the main window.\n\
Here you will watch a simulation progressing over the time.\n\
Please consider opening a .simulation file, -- or defining a new simulation\n\
by opening a .scene file and setting up some parameters through the \
dialogs.\n\
Then you will use the stop-play-pause buttons to control the simulation.", 40},
  {"The value entered for `number of steps' is not valid.", 41},
  {"The value entered for `display frequency' is not valid.", 42},
  {"File not found !", 43},
  {"Computing...", 44},
  {"\
Error while reading the file...\n\
Are you sure this is a .simul file?", 45},
  {"Fileread failed.", 46},
  {"Grany-3 : ", 47},
  {"\
Error while writing the file...\n\
Do you have write permission?", 48},
  {"Grany-3 : new file", 49},
  {"You have erased the previous file named :\n", 50},
  {"Step of the automata : ", 51},
  {"The value entered for `network size' is not valid. It must be a number.", 52},
  {"\
The value entered for `network size' is not valid.\n\
It must be greater than 0. (and should be smaller than 100 to be viewable)", 53},
  {"\
The -actual- number of cells generated is `network size'^2.\n\
The cells in the window can therefore be too small to be viewable.", 54},
  {"\
The value entered for `number of steps' is not valid. It must be a number.", 55},
  {"\
The value entered for `number of steps' is not valid. It must be greater \
than 0.", 56},
  {"The value entered for `seed' is not valid.", 57},
  {"\
Error while reading the file...\n\
Are you sure you gave me a .scene file?", 58},
  {"New", 59},
  {"Open", 60},
  {"Save", 61},
  {"Help", 62},
  {"_New", 63},
  {"<alt>n", 64},
  {"_Open", 65},
  {"_Save", 66},
  {"Save as...", 67},
  {"_Quit", 68},
  {"<alt>q", 69},
  {"_File", 70},
  {"<alt>f", 71},
  {"Open a file...", 72},
  {"Write to a file...", 73},
  {"About _Grany", 74},
  {"Ne_wbie help!", 75},
  {"_Help", 76},
  {"<alt>h", 77},
  {"Sorry, no newbie help available in this window.", 78},
  {"version", 79},
  {"engine, file handling, tools (autoconf...)", 80},
  {"graphical interface", 81},
  {"hexagonal algorithms", 82},
  {"design", 83},
  {"contribution to the graphical interface", 84},
  {"contribution to file handling", 85},
  {"Usage", 86},
  {"Launch the graphical interface of Grany-3", 87},
  {"Options", 88},
  {"disable the (few) warning messages", 89},
  {"prints a summary of the options", 90},
  {"prints the version number", 91},
  {"prints the authors", 92},
  {"Now I can talk like this. Your application will be in english.", 93},
  {"Expert mode engaged.", 94},
  {"[Warning!] Unrecognized option on command-line: ", 95},
  {"Asking gtk to wake up...", 96},
  {"No ~/.grany/granyrc, so using common `granyrc'.", 97},
  {"Found ~/.grany/granyrc, using it.", 98},
  {"Ok. Running now...", 99},
  {"Exiting...", 100},
  {"Borders editor : new file", 101},
  {"Select", 102},
  {"New line", 103},
  {"New arc of ellipse", 104},
  {"New ellipse", 105},
  {"New polygon", 106},
  {"Delete", 107},
  {"Create classical borders", 108},
  {"Create generating borders", 109},
  {"Grid", 110},
  {"_Edit", 111},
  {"<alt>e", 112},
  {"Configuration in progress...", 113},
  {"\
Error while reading the file...\n\
Are you sure this was a borders file?", 114},
  {"Borders editor : ", 115},
  {"Error while writing the file...", 116},
  {"\
This is the Borders Editor.\n\
Here you will design the borders of a future simulation.\n\
\n\
You can use several geometrical forms:\n\
1. A line: click-drag-drop.\n\
2. An arc of ellipse: click-drag-drop to setup the first and last points ; \
then move the pointer to setup the curve.\n\
3. An ellipse: click-drag-drop (holding shift you will create a circle).\n\
4. A polygon: click-drag-drop for the first line, then click for the next \
ones, then right-click to terminate.\n\
\n\
Each one of these borders may be:\n\
1. Classical borders. -- or,\n\
2. Generating borders (which means one phase will be able to go through this \
border).", 117},
  {"Element selected.", 118},
  {"New line, origine : (", 119},
  {"). Drag for the end.", 120},
  {"The arc of ellipse is not valid.", 121},
  {"Arc of ellipse with a classical border added.", 122},
  {"Arc of ellipse with a generating border added.", 123},
  {"New arc of ellipse, origine : (", 124},
  {"The line is not valid.", 125},
  {"Left button for another line, right button to end.", 126},
  {"The polygone is not valid.", 127},
  {"Polygone with a classical border added.", 128},
  {"Polygone with a generating border added.", 129},
  {"New polygone, origine : (", 130},
  {"). Drag.", 131},
  {"New ellipse, origine : (", 132},
  {"Current position : (", 133},
  {"Line with classical border added.", 134},
  {"Line with generating border added.", 135},
  {"Invalid arc of ellipse.", 136},
  {"Now decide for the centre of the ellipse.", 137},
  {"The line is not valid. Please give the first line again.", 138},
  {"The ellipse is not valid.", 139},
  {"Ellipse with classical border added.", 140},
  {"Ellipse with generating border added.", 141},
  {"Element deleted.", 142},
  {"You can also use the DEL key.", 143},
  {"Add a new line by clicking for the origine, then dragging for the end.", 144},
  {"\
Add a new arc of ellipse by clicking and dragging to determine the extreme \
coordinates.", 145},
  {"\
Add a new ellipse by clicking and dragging to determine the extreme \
coordinates.", 146},
  {"Add a new polygone by clicking and dragging for the first line.", 147},
  {"Added borders will be `classical'.", 148},
  {"Added borders will be `generating'.", 149},
  {"The grid is no longer displayed.", 150},
  {"The grid is being displayed.", 151},
  {"Modify", 152},
  {"Borders", 153},
  {"Properties", 154},
  {"Propagative", 155},
  {"Generated", 156},
  {"Phases", 157},
  {"Number of phases : 0", 158},
  {"Zoning", 159},
  {"Coloration", 160},
  {"Scene editor : new file", 161},
  {"\
Error while reading the file...\n\
Are you sur this was a .scene file?", 162},
  {"Scene editor : ", 163},
  {"You must define at least one border.", 164},
  {"You must define at least one phase.", 165},
  {"You must define a generated phase because you have a generating border.", 166},
  {"You must define at least one zoning.", 167},
  {"Scene editor", 168},
  {"\
This is the Scene Editor.\n\
Here you will design step-by-step a new scene (ie. a vectorial \
representation of the future simulation):\n\
1. Design some borders either by opening a borders file or creating a new \
one from scratch.\n\
2. Design some phases (abstraction for `type of matter') and setup their \
properties.\n\
3. Design some zonings: they will be the initial positions of the phases.\n\
4. Design some colorations: they will repaint some initial areas with local \
colors.", 169},
  {"Open a borders file...", 170},
  {"No phase selected.", 171},
  {"Number of phases : ", 172},
  {"Newphase", 173},
  {"Rules editor", 174},
  {"Same Phi", 175},
  {"Lower than solid Phi", 176},
  {"Lower Phi", 177},
  {"Any Phi", 178},
  {"Ready", 179},
  {"Now, to enable the rule, that cell must be `same phi'", 180},
  {"Now, to enable the rule, that cell must be `phi inf solid'", 181},
  {"Now, to enable the rule, that cell must be `phi inf'", 182},
  {"Now, there is no constraint on this cell", 183},
  {"Now, this movement is allowed", 184},
  {"Now, this movement is forbidden", 185},
  {"Rules editor : new file", 186},
  {"\
Error while reading the file...\n\
Are you sure this was a rule file?", 187},
  {"Rules editor : ", 188},
  {"\
The value entered for `name' is not valid. It must not contain spaces nor \
special characters.", 189},
  {"\
This is the Rules Editor.\n\
Here you will design an exclusion rule applicable to the phases.\n\
To setup your rule, you may:\n\
1. dictate conditions on the neighbourhood by the colors symbols.\n\
2. forbid some movements by clicking on the arrows.", 190},
  {"Clic on a bubble to set it `same phi'", 191},
  {"Clic on a bubble to set it `lower than solid Phi'", 192},
  {"Clic on a bubble to set it `lower phi'", 193},
  {"Clic on a bubble to set it `any phi'", 194},
  {"Scene name", 195},
  {"Parameters", 196},
  {"Ok", 197},
  {"Cancel", 198},
  {"Browse...", 199},
  {"Network size", 200},
  {"Number of steps", 201},
  {"Seed", 202},
  {"New simulation", 203},
  {"Open a scene file...", 204},
  {"General", 205},
  {"Display frequency", 206},
  {"Apply changes", 207},
  {"Updatable parameters", 208},
  {"Name of output file", 209},
  {"Recording parameters", 210},
  {"Sorry, not implemented.", 211},
  {"The phase is solid", 212},
  {"The phase is fluid", 213},
  {"Name :", 214},
  {"Inertia :", 215},
  {"Color", 216},
  {"Rules", 217},
  {"Usable rules", 218},
  {"Pre-exclusion rules", 219},
  {"Post-exclusion rules", 220},
  {"Design new rule", 221},
  {"Add in pre ", 222},
  {"Add in post", 223},
  {"Remove from pre ", 224},
  {"Remove from post", 225},
  {"Ponderations", 226},
  {"North", 227},
  {"South", 228},
  {"North-east", 229},
  {"North-west", 230},
  {"South-east", 231},
  {"South-west", 232},
  {"Phases parameters", 233},
  {"Please choose a color...", 234},
  {"Please save the rule in the rules editor", 235},
  {"\
Error while reading the rule file. Reinstall Microsoft Windows.\n\
(seriously, you're in trouble)", 236},
  {"No rule selected.", 237},
  {"The value entered for `name' is not valid. It must not be void.", 238},
  {"\
The value entered for `name' is not valid. It must be different from the \
other phases names.", 239},
  {"The value entered for `inertie' is not valid. It must be a number.", 240},
  {"The value entered for `North' is not valid. It must be a number.", 241},
  {"The value entered for `North east' is not valid. It must be a number.", 242},
  {"The value entered for `North west' is not valid. It must be a number.", 243},
  {"The value entered for `South' is not valid. It must be a number.", 244},
  {"The value entered for `South east' is not valid. It must be a number.", 245},
  {"The value entered for `South west' is not valid. It must be a number.", 246},
  {"Relative mix of phases:", 247},
  {"Apply mix to selected area", 248},
  {"Zoning editor", 249},
  {"\
This is the Zoning Editor.\n\
Here you will setup the initial positions of the phases:\n\
1. Setup the desired phases mix with the sliders on the right.\n\
2. Create your geometrical filled form:\n\
\ta. A rectangle or an ellipse by click-drag-drop.\n\
\tb. A polygon by click-drag-drop, then clicks, then right-click.", 250},
  {"New rectangle, origine : (", 251},
  {"You must have at least a little bit of one phase !", 252},
  {"The rectangle is not valid.", 253},
  {"Rectangle added.", 254},
  {"No area selected !", 255},
  {"An error has occured...", 256},
  {"Error", 257},
  {"New rectangle", 258},
  {"\
Add a new rectangle by clicking for the origine, then dragging for the end.", 259},
  {"Add a new ellipse by clicking and dragging.", 260},
  {"Choose color", 261},
  {"Automatic random color", 262},
  {"Coloration editor", 263},
  {"\
This is the Coloration Editor.\n\
Here you will setup color paintings on some areas:\n\
1. Setup the desired color.\n\
2. Create your geometrical filled form:\n\
\ta. A rectangle or an ellipse by click-drag-drop.\n\
\tb. A polygon by click-drag-drop, then clicks, then right-click.", 264},
  {"A newbie! has occured...", 265},
  {"Newbie", 266},
  {"You did not specify the network size.", 267},
  {"console", 268},
  {"This is", 269},
  {"the celullar automaton simulator.", 270},
  {"Launch the simulation or the scene from FILE or standard input", 271},
  {"seed of the simulation", 272},
  {"number of steps of the simulation", 273},
  {"if the argument is a scene, gives the dimension of the network", 274},
  {"file handling, engine, tools (configure...)", 275},
};

int _msg_tbl_length = 275;
