#ifndef FLEX_HEADER_RegleScanner_h
#define FLEX_HEADER_RegleScanner_h
#define YY_RegleScanner_CHAR unsigned char
#line 1 "/tmp/flex++/tools/lib/flexskel.h"
/* A lexical scanner header generated by flex */
/* MODIFIED FOR C++ CLASS BY Alain Coetmeur: coetmeur(at)icdc.fr */
/* Note that (at) mean the 'at' symbol that I cannot write */
/* because it is expanded to the class name */
/* made at Informatique-CDC, Research&development department */
/* company from the Caisse Des Depots et Consignations */


/*********************************************/
/* SYSTEM dependent declaration, includes... */
/*********************************************/
/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif
#ifdef __cplusplus
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#ifndef YY_USE_CLASS
#define YY_USE_CLASS
#endif
#else	/* ! __cplusplus */
#ifdef __STDC__
#ifdef __GNUC__
#else
#endif	/* __GNUC__ */
#ifndef YY_USE_PROTOS
#define YY_USE_PROTOS
#endif
#endif	/* __STDC__ */
#endif	/* ! __cplusplus */
/*********************************************/
/* COMPILER DEPENDENT   MACROS               */
/*********************************************/
/* use prototypes in function declarations */
#ifndef YY_PROTO
#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif
#endif
#include <stdio.h>




/* % here is the declaration from section1 %header{  */ 
#line 19 "RegleScanner.l"
#define YY_RegleScanner_LEX_PARAM  YY_RegleParser_STYPE *val,YY_RegleParser_LTYPE *loc
#line 20 "RegleScanner.l"
#define YY_RegleScanner_IOSTREAM 
#line 21 "RegleScanner.l"
#define YY_RegleScanner_MEMBERS  \
   public: \
      int _ligne, _colonne; \
      void beginAction();
#line 26 "RegleScanner.l"
#define YY_RegleScanner_CONSTRUCTOR_INIT  : _ligne(1), _colonne(1)
#line 29 "RegleScanner.l"
#include "RegleParser.h"

#define YY_USER_ACTION beginAction();
#line 45 "RegleScanner.l"
#line 52 "/tmp/flex++/tools/lib/flexskel.h"

#ifdef YY_USE_CLASS
#ifdef YY_RegleScanner_IOSTREAM
#include <iostream>
#define YY_RegleScanner_IFILE  istream
#define YY_RegleScanner_OFILE ostream 
#define YY_RegleScanner_ERRFILE cerr

#ifndef YY_RegleScanner_IFILE_DEFAULT
#define YY_RegleScanner_IFILE_DEFAULT &cin
#endif

#ifndef YY_RegleScanner_OFILE_DEFAULT
#define YY_RegleScanner_OFILE_DEFAULT &cout
#endif

#endif
#endif

#ifndef YY_RegleScanner_IFILE
#define YY_RegleScanner_IFILE FILE 
#endif

#ifndef YY_RegleScanner_OFILE
#define YY_RegleScanner_OFILE FILE 
#endif

#ifndef YY_RegleScanner_ERRFILE
#define YY_RegleScanner_ERRFILE stderr
#endif

#ifndef YY_RegleScanner_IFILE_DEFAULT
#define YY_RegleScanner_IFILE_DEFAULT stdin
#endif

#ifndef YY_RegleScanner_OFILE_DEFAULT
#define YY_RegleScanner_OFILE_DEFAULT stdout
#endif




#ifndef YY_RegleScanner_TEXT
#define YY_RegleScanner_TEXT yytext
#endif
#ifndef YY_RegleScanner_LENG
#define YY_RegleScanner_LENG yyleng
#endif
#ifndef YY_RegleScanner_IN
#define YY_RegleScanner_IN yyin
#endif
#ifndef YY_RegleScanner_OUT
#define YY_RegleScanner_OUT yyout
#endif

#ifndef YY_RegleScanner_LEX_RETURN
#define YY_RegleScanner_LEX_RETURN int
#else
#ifndef YY_RegleScanner_LEX_DEFINED
#define YY_RegleScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_RegleScanner_LEX
#define YY_RegleScanner_LEX yylex
#else
#ifndef YY_RegleScanner_LEX_DEFINED
#define YY_RegleScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_RegleScanner_LEX_PARAM
#ifndef YY_USE_PROTOS
#define YY_RegleScanner_LEX_PARAM 
#else
#define YY_RegleScanner_LEX_PARAM void
#endif
#else
#ifndef YY_RegleScanner_LEX_DEFINED
#define YY_RegleScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_RegleScanner_LEX_PARAM_DEF
#define YY_RegleScanner_LEX_PARAM_DEF
#else
#ifndef YY_RegleScanner_LEX_DEFINED
#define YY_RegleScanner_LEX_DEFINED 
#endif
#endif

#ifndef YY_RegleScanner_RESTART
#define YY_RegleScanner_RESTART yyrestart
#endif
#ifndef YY_RegleScanner_SWITCH_TO_BUFFER
#define YY_RegleScanner_SWITCH_TO_BUFFER yy_switch_to_buffer
#endif
#ifndef YY_RegleScanner_LOAD_BUFFER_STATE
#define YY_RegleScanner_LOAD_BUFFER_STATE yy_load_buffer_state
#endif

#ifndef YY_RegleScanner_CREATE_BUFFER
#define YY_RegleScanner_CREATE_BUFFER yy_create_buffer
#ifndef YY_USE_CLASS
#ifndef yy_new_buffer
#define yy_new_buffer yy_create_buffer
#endif
#endif
#endif
#ifndef YY_RegleScanner_DELETE_BUFFER
#define YY_RegleScanner_DELETE_BUFFER yy_delete_buffer
#endif
#ifndef YY_RegleScanner_INIT_BUFFER
#define YY_RegleScanner_INIT_BUFFER yy_init_buffer
#endif



#ifdef YY_RegleScanner_FLEX_DEBUG
#ifndef YY_RegleScanner_DEBUG
#define YY_RegleScanner_DEBUG 1
#endif
#else
#ifndef YY_RegleScanner_DEBUG
#define YY_RegleScanner_DEBUG 0
#endif
#endif

#if YY_RegleScanner_DEBUG != 0
#ifndef YY_RegleScanner_DEBUG_FLAG
#define YY_RegleScanner_DEBUG_FLAG yy_flex_debug
#endif
#ifndef YY_RegleScanner_DEBUG_INIT
#define YY_RegleScanner_DEBUG_INIT 1
#endif
#endif




#ifndef YY_USE_CLASS
#ifndef YY_RegleScanner_CURRENT_BUFFER
#define YY_RegleScanner_CURRENT_BUFFER yy_current_buffer
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern void YY_RegleScanner_RESTART YY_PROTO(( YY_RegleScanner_IFILE *input_file ));
extern void YY_RegleScanner_SWITCH_TO_BUFFER YY_PROTO(( YY_BUFFER_STATE new_buffer ));
extern void YY_RegleScanner_LOAD_BUFFER_STATE YY_PROTO(( void ));
extern YY_BUFFER_STATE YY_RegleScanner_CREATE_BUFFER YY_PROTO(( YY_RegleScanner_IFILE *file, int size ));
extern void YY_RegleScanner_DELETE_BUFFER YY_PROTO(( YY_BUFFER_STATE b ));
extern void YY_RegleScanner_INIT_BUFFER YY_PROTO(( YY_BUFFER_STATE b, YY_RegleScanner_IFILE *file ));

#if YY_RegleScanner_DEBUG != 0
extern int YY_RegleScanner_DEBUG_FLAG ;
#endif
extern YY_RegleScanner_CHAR  *YY_RegleScanner_TEXT;
extern int YY_RegleScanner_LENG;
extern YY_RegleScanner_IFILE *YY_RegleScanner_IN;
extern YY_RegleScanner_OFILE *YY_RegleScanner_OUT;
#ifdef YY_RegleScanner_LEX_DEFINED
extern YY_RegleScanner_LEX_RETURN YY_RegleScanner_LEX ( YY_RegleScanner_LEX_PARAM )
YY_RegleScanner_LEX_PARAM_DEF
#else
#ifndef YY_DECL
extern YY_RegleScanner_LEX_RETURN YY_RegleScanner_LEX ( YY_RegleScanner_LEX_PARAM )
YY_RegleScanner_LEX_PARAM_DEF
#else
/* no declaration if oldstyle flex */
#endif
#endif
#else

#ifndef YY_RegleScanner_CURRENT_BUFFER
#define YY_RegleScanner_CURRENT_BUFFER YY_CURRENT_BUFFER
#endif
#ifndef YY_RegleScanner_CLASS
#define YY_RegleScanner_CLASS RegleScanner
#endif
#ifndef YY_RegleScanner_ECHO
#define YY_RegleScanner_ECHO yy_echo
#endif
#ifdef YY_RegleScanner_ECHO_PURE
#define YY_RegleScanner_ECHO_NOCODE
#endif

#ifndef YY_RegleScanner_ECHO_CODE
#ifndef YY_RegleScanner_IOSTREAM
#define YY_RegleScanner_ECHO_CODE fwrite( (char *) YY_RegleScanner_TEXT, YY_RegleScanner_LENG, 1, YY_RegleScanner_OUT );
#else
#define YY_RegleScanner_ECHO_CODE (YY_RegleScanner_OUT->write( (char *) YY_RegleScanner_TEXT, YY_RegleScanner_LENG));
#endif
#endif

#ifndef YY_RegleScanner_INPUT
#define YY_RegleScanner_INPUT yy_input
#endif
#ifdef YY_RegleScanner_INPUT_PURE
#define YY_RegleScanner_INPUT_NOCODE
#endif

#ifndef YY_RegleScanner_INPUT_CODE
#ifndef YY_RegleScanner_IOSTREAM
#define YY_RegleScanner_INPUT_CODE return result= fread(  buffer, 1,max_size,YY_RegleScanner_IN );
#else
#define YY_RegleScanner_INPUT_CODE if(YY_RegleScanner_IN->eof())  result=0;else {YY_RegleScanner_IN->read(buffer,max_size);result=YY_RegleScanner_IN->gcount();YY_RegleScanner_IN->clear(YY_RegleScanner_IN->rdstate()&(~ios::failbit));if(YY_RegleScanner_IN->bad()) result= -1;} return result;
#endif
#endif

#ifdef YY_RegleScanner_FATAL_ERROR_PURE
#define YY_RegleScanner_FATAL_ERRO_NOCODE
#endif
#ifndef YY_RegleScanner_FATAL_ERROR
#define YY_RegleScanner_FATAL_ERROR yy_fatal_error
#endif

#ifndef YY_RegleScanner_FATAL_ERROR_CODE
#ifndef YY_RegleScanner_IOSTREAM
#define YY_RegleScanner_FATAL_ERROR_CODE fputs( msg, YY_RegleScanner_ERRFILE );putc( '\n', YY_RegleScanner_ERRFILE );exit( 1 );
#else
#define YY_RegleScanner_FATAL_ERROR_CODE YY_RegleScanner_ERRFILE<< msg <<endl;exit( 1 );
#endif
#endif

#ifndef YY_RegleScanner_WRAP
#define YY_RegleScanner_WRAP yy_wrap
#endif
#ifdef YY_RegleScanner_WRAP_PURE
#define YY_RegleScanner_WRAP_NOCODE
#endif
#ifndef YY_RegleScanner_WRAP_CODE
#define YY_RegleScanner_WRAP_CODE return 1;
#endif


#ifndef YY_RegleScanner_INHERIT
#define YY_RegleScanner_INHERIT
#endif
#ifndef YY_RegleScanner_MEMBERS
#define YY_RegleScanner_MEMBERS 
#endif
#ifndef YY_RegleScanner_CONSTRUCTOR_PARAM
#define YY_RegleScanner_CONSTRUCTOR_PARAM
#endif
#ifndef YY_RegleScanner_CONSTRUCTOR_CODE
#define YY_RegleScanner_CONSTRUCTOR_CODE
#endif
#ifndef YY_RegleScanner_CONSTRUCTOR_INIT
#define YY_RegleScanner_CONSTRUCTOR_INIT
#endif
#ifndef YY_RegleScanner_DESTRUCTOR_CODE
#define YY_RegleScanner_DESTRUCTOR_CODE
#endif
typedef struct yy_buffer_state *YY_BUFFER_STATE;

class YY_RegleScanner_CLASS YY_RegleScanner_INHERIT
{
 private:/* data */
 YY_RegleScanner_CHAR  *yy_c_buf_p;
 YY_RegleScanner_CHAR  yy_hold_char;
 int yy_n_chars;
 int yy_init;
 int yy_start;
 int yy_did_buffer_switch_on_eof;
 private: /* functions */
 void yy_initialize();
 int input();
 int yyinput() {return input();};
 int yy_get_next_buffer();
 void yyunput( YY_RegleScanner_CHAR  c, YY_RegleScanner_CHAR  *buf_ptr );
 /* use long instead of yy_state_type because it is undef */
 long yy_get_previous_state_ ( void );
 long yy_try_NUL_trans_  ( long current_state_ );
 protected:/* non virtual */
 YY_BUFFER_STATE YY_RegleScanner_CURRENT_BUFFER;
 void YY_RegleScanner_RESTART ( YY_RegleScanner_IFILE *input_file );
 void YY_RegleScanner_SWITCH_TO_BUFFER( YY_BUFFER_STATE new_buffer );
 void YY_RegleScanner_LOAD_BUFFER_STATE( void );
 YY_BUFFER_STATE YY_RegleScanner_CREATE_BUFFER( YY_RegleScanner_IFILE *file, int size );
 void YY_RegleScanner_DELETE_BUFFER( YY_BUFFER_STATE b );
 void YY_RegleScanner_INIT_BUFFER( YY_BUFFER_STATE b, YY_RegleScanner_IFILE *file );
 protected: /* virtual */
 virtual void YY_RegleScanner_ECHO()
#ifdef YY_RegleScanner_ECHO_PURE
  =0
#endif
  ;
 virtual int  YY_RegleScanner_INPUT(char  *buf,int &result,int max_size)
#ifdef YY_RegleScanner_INPUT_PURE
  =0
#endif
  ;
 virtual void  YY_RegleScanner_FATAL_ERROR(char *msg)
#ifdef YY_RegleScanner_FATAL_ERROR_PURE
  =0
#endif
  ;
 virtual int  YY_RegleScanner_WRAP()
#ifdef YY_RegleScanner_WRAP_PURE
  =0
#endif
  ;
 public:
 YY_RegleScanner_CHAR  *YY_RegleScanner_TEXT;
 int YY_RegleScanner_LENG;
 YY_RegleScanner_IFILE *YY_RegleScanner_IN;
 YY_RegleScanner_OFILE *YY_RegleScanner_OUT;
 YY_RegleScanner_LEX_RETURN YY_RegleScanner_LEX ( YY_RegleScanner_LEX_PARAM);
 YY_RegleScanner_CLASS(YY_RegleScanner_CONSTRUCTOR_PARAM) ;
 virtual ~YY_RegleScanner_CLASS() ;
#if YY_RegleScanner_DEBUG != 0
 int YY_RegleScanner_DEBUG_FLAG;
#endif
 public: /* added members */
 YY_RegleScanner_MEMBERS 
};
#endif



/* declaration of externs for public use of yylex scanner */

/* % here is the declaration from section2 %header{ */ 
#line 59 "RegleScanner.l"
#endif
#line 375 "/tmp/flex++/tools/lib/flexskel.h"

/* end of generated header */
